package newDemoQaPages.demoInvoiceReviewPage.potentialSavingsCardModals;

import newDemoQaPages.demoPriorAgreementComparisonPage.refundsForLateShipment.PotentialCreditsRefundsModalFirstLevel;

public class PotentialSavingsCardModalFirstLevel extends PotentialCreditsRefundsModalFirstLevel {
}
