package newDemoQaPages.demoInvoiceReviewPage.potentialSavingsCardModals;

import newDemoQaPages.demoPriorAgreementComparisonPage.refundsForLateShipment.PotentialCreditsRefundsModalSecondLevel;

public class PotentialSavingsCardModalSecondLevel extends PotentialCreditsRefundsModalSecondLevel {
}
